---
version: '3.7'

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=performer
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database:/data/db
    ports:
      - '27017-27019:27017-27019'
  whoami:
    image: traefik/whoami
    #ports:
    #  - '8090:80'
  traefik:
    image: traefik:v2.6.1
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP/S port
      - '80:80'
      - '443:443'
      # The Traefik Web UI (enabled by --api.insecure=true)
      - '8080:8080'
      # Template servers
      # - '8090:8090'
      # - '8081:8081'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/configuration/:/configuration/:ro
      # - ./certs/:/tmp/certs/:ro
