## traefik.yml

# Docker configuration backend
providers:
  docker:
    #endpoint: "unix:///var/run/docker.sock"
    # Add service only by traefik.enable=true
    exposedByDefault: false
  file:
    directory: /configuration
    watch: true

# API and dashboard configuration
api:
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'
    #http:
    #  redirections:
    #    entryPoint:
    #      to: websecure
    #      scheme: https

  websecure:
    address: ':443'

  #server:
  #  address: ':8090'
  # template-port.yml servers
  #client-port:
  #  address: ':8081'
