# strip path prefixes
{{$services := dict}}
{{$_ := set $services "whoami" "http://whoami"}}

http:
  middlewares:
    {{range $name, $url := $services}}
    strip-{{ $name }}:
      stripPrefix:
        prefixes:
          - "/{{ $name }}"
    {{end}}
  routers:
    {{range $name, $url := $services}}
    {{ $name }}:
      entryPoints:
        # - "websecure"
        - "web"
      service: service-{{ $name }}
      # tls: {}
      rule: PathPrefix(`/{{ $name }}`)
      middlewares:
        - 'cors-headers'
        - "strip-{{ $name }}"
    {{end}}
  services:
    {{range $name, $url := $services}}
    service-{{ $name }}:
      loadBalancer:
        servers:
          - url: {{ $url }}
        passHostHeader: true
    {{end}}
