{{$servicesPorts := dict}}
{{$_ := set $servicesPorts "client-port" "http://192.168.30.80:3000"}}

http:
  routers:   
    {{range $name, $url := $servicesPorts}}
    {{ $name }}:
      entryPoints:
        - {{ $name }}
      service: service-{{ $name }}
      # tls: {}
      rule: HostRegexp(`{host:.+}`)
    {{end}}
  services:
    {{range $name, $url := $servicesPorts}}
    service-{{ $name }}:
      loadBalancer:
        servers:
          - url: {{ $url }}
        passHostHeader: true
    {{end}}

